### ISSUE TITLE
website should have a dedicated download page

### ISSUE THREAD

**Issue by pacharanero** [NHSbuntu/www.nhsbuntu.org#22] opened 2017-04-27 20:38 UTC
as a user wanting to download NHSbuntu
I should be able to click on a download tab
and see the available downloads, including current stable x64, 32bit, ARM, and virtualbox image/vagrant boxen

**Comment by robdyke** [comment] 2017-05-18 22:34
Duplicate of #26

Closing

**Closed by robdyke** 2017-05-18 22:34 UTC
